"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from './components/Footer';
import {usePathname} from "next/navigation";

import Sidenav from './components/Sidenav';
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Dementia App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      </head>
      {pathname=="/" || pathname=="/login" || pathname=="/register" ?
      (
        <body className={inter.className}>
        {children}
        <Footer />
      </body>
      ):(
        <body className={inter.className}>
        <Sidenav/>
        {children}
        <Footer />  
        </body>
      )
      }
      
    </html>
  )
}
